# Generated by Django 4.1 on 2024-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=500, null=True)),
                ('created_by', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'ip',
            },
        ),
    ]
